// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_WEB_API_KEY', defaultValue: 'AIzaSyBuivCVQhLHrzdXV4-YIfThRFeZZqwLHO8'),
    authDomain: const String.fromEnvironment('FIREBASE_AUTH_DOMAIN', defaultValue: 'housekeepr-51a2e.firebaseapp.com'),
    projectId: const String.fromEnvironment('FIREBASE_PROJECT_ID', defaultValue: 'housekeepr-51a2e'),
    storageBucket: const String.fromEnvironment('FIREBASE_STORAGE_BUCKET', defaultValue: 'housekeepr-51a2e.firebasestorage.app'),
    messagingSenderId: const String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID', defaultValue: '480693965267'),
    appId: const String.fromEnvironment('FIREBASE_APP_ID', defaultValue: '1:480693965267:web:4a5e4162c2d003ccdb1f26'),
    measurementId: const String.fromEnvironment('FIREBASE_MEASUREMENT_ID', defaultValue: 'G-H5LTCWWLWL'),
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_ANDROID_API_KEY', defaultValue: 'AIzaSyBL9xBhDYhRqTvEVNounPVrV3tuhkCLddw'),
    appId: const String.fromEnvironment('FIREBASE_ANDROID_APP_ID', defaultValue: '1:480693965267:android:3223c47031045895db1f26'),
    messagingSenderId: const String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID', defaultValue: '480693965267'),
    projectId: const String.fromEnvironment('FIREBASE_PROJECT_ID', defaultValue: 'housekeepr-51a2e'),
    storageBucket: const String.fromEnvironment('FIREBASE_STORAGE_BUCKET', defaultValue: 'housekeepr-51a2e.firebasestorage.app'),
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_IOS_API_KEY', defaultValue: 'AIzaSyBdoeztekgTlhnpUSvWYnGtkoRseXFWJn8'),
    appId: const String.fromEnvironment('FIREBASE_IOS_APP_ID', defaultValue: '1:480693965267:ios:174093ecd82343afdb1f26'),
    messagingSenderId: const String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID', defaultValue: '480693965267'),
    projectId: const String.fromEnvironment('FIREBASE_PROJECT_ID', defaultValue: 'housekeepr-51a2e'),
    storageBucket: const String.fromEnvironment('FIREBASE_STORAGE_BUCKET', defaultValue: 'housekeepr-51a2e.firebasestorage.app'),
    iosBundleId: const String.fromEnvironment('FIREBASE_IOS_BUNDLE_ID', defaultValue: 'com.example.housekeepr'),
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_MACOS_API_KEY', defaultValue: 'AIzaSyBdoeztekgTlhnpUSvWYnGtkoRseXFWJn8'),
    appId: const String.fromEnvironment('FIREBASE_MACOS_APP_ID', defaultValue: '1:480693965267:ios:174093ecd82343afdb1f26'),
    messagingSenderId: const String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID', defaultValue: '480693965267'),
    projectId: const String.fromEnvironment('FIREBASE_PROJECT_ID', defaultValue: 'housekeepr-51a2e'),
    storageBucket: const String.fromEnvironment('FIREBASE_STORAGE_BUCKET', defaultValue: 'housekeepr-51a2e.firebasestorage.app'),
    iosBundleId: const String.fromEnvironment('FIREBASE_IOS_BUNDLE_ID', defaultValue: 'com.example.housekeepr'),
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_WINDOWS_API_KEY', defaultValue: 'AIzaSyBuivCVQhLHrzdXV4-YIfThRFeZZqwLHO8'),
    appId: const String.fromEnvironment('FIREBASE_WINDOWS_APP_ID', defaultValue: '1:480693965267:web:05e2fd6bbdd7cabfdb1f26'),
    messagingSenderId: const String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID', defaultValue: '480693965267'),
    projectId: const String.fromEnvironment('FIREBASE_PROJECT_ID', defaultValue: 'housekeepr-51a2e'),
    authDomain: const String.fromEnvironment('FIREBASE_AUTH_DOMAIN', defaultValue: 'housekeepr-51a2e.firebaseapp.com'),
    storageBucket: const String.fromEnvironment('FIREBASE_STORAGE_BUCKET', defaultValue: 'housekeepr-51a2e.firebasestorage.app'),
    measurementId: const String.fromEnvironment('FIREBASE_MEASUREMENT_ID', defaultValue: 'G-689BCCEXN9'),
  );
}
