name: Flutter Analyze

on:
  push:
    branches: [ FlutterApp, main, master ]
  pull_request:
    branches: [ FlutterApp, main, master ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 'latest'

      - name: Cache Pub packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: |
          flutter pub get
        working-directory: ./

      - name: Run flutter analyze for housekeepr package
        run: |
          cd housekeepr
          flutter analyze --no-fatal-infos
